class Opcodes{
	static ADC(){return 0}
	static AND(){return 0}
	static ASL(){return 0}
	static BCC(){return 0}
	static BCS(){return 0}
	static BEQ(){return 0}
	static BIT(){return 0}
	static BMI(){return 0}
	static BNE(){return 0}
	static BPL(){return 0}
	static BRK(){return 0}
	static BVC(){return 0}
	static BVS(){return 0}
	static CLC(){return 0}
	static CLD(){return 0}
	static CLI(){return 0}
	static CLV(){return 0}
	static CMP(){return 0}
	static CPX(){return 0}
	static CPY(){return 0}
	static DEC(){return 0}
	static DEX(){return 0}
	static DEY(){return 0}
	static EOR(){return 0}
	static INC(){return 0}
	static INX(){return 0}
	static INY(){return 0}
	static JMP(){return 0}
	static JSR(){return 0}
	static LDA(){return 0}
	static LDX(){return 0}
	static LDY(){return 0}
	static LSR(){return 0}
	static NOP(){return 0}
	static ORA(){return 0}
	static PHA(){return 0}
	static PHP(){return 0}
	static PLA(){return 0}
	static PLP(){return 0}
	static ROL(){return 0}
	static ROR(){return 0}
	static RTI(){return 0}
	static RTS(){return 0}
	static SBC(){return 0}
	static SEC(){return 0}
	static SED(){return 0}
	static SEI(){return 0}
	static STA(){return 0}
	static STX(){return 0}
	static STY(){return 0}
	static TAX(){return 0}
	static TAY(){return 0}
	static TSX(){return 0}
	static TXA(){return 0}
	static TXS(){return 0}
	static TYA(){return 0}
	static XXX(){return 0}
}

export default Opcodes;